name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # 1. Crear el proyecto Android primero (genera android/app/)
      - run: npx cap add android

      # 2. Ahora sí, restaurar google-services.json desde el secreto base64
      - name: Restaurar google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - run: npx cap sync

      # Añadir permisos de Android (ya incluye POST_NOTIFICATIONS)
      - name: Añadir Permisos de Android
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i 's|</manifest>|    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\n    <uses-feature android:name="android.hardware.location.gps" />\n    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\n    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />\n</manifest>|g' $MANIFEST

      - run: cd android && chmod +x gradlew && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Aguabol-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
